-- Enable UUID extension (Required for Supabase if not already enabled)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Create "products" table
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_en TEXT NOT NULL,
    title_th TEXT NOT NULL,
    category TEXT NOT NULL,
    price NUMERIC NOT NULL,
    image_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Insert 6 sample products
INSERT INTO products (title_en, title_th, category, price, image_url, is_active) VALUES
('Signature Espresso', 'ซิกเนเจอร์ เอสเพรสโซ่', 'coffee', 4.50, 'https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&q=80&w=400', true),
('Iced Caramel Macchiato', 'คาราเมลมัคคิอาโต้เย็น', 'coffee', 5.50, 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=400', true),
('Matcha Green Tea Latte', 'มัทฉะกรีนทีลาเต้', 'tea', 5.00, 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&q=80&w=400', true),
('Classic Croissant', 'ครัวซองต์เนยสด', 'bakery', 3.50, 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&q=80&w=400', true),
('Earl Grey Tea', 'ชาเอิร์ลเกรย์', 'tea', 3.00, 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=400', true),
('Chocolate Muffin', 'ช็อกโกแลตมัฟฟิน', 'bakery', 4.00, 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&q=80&w=400', true);

-- 2. Create "bookings" table
CREATE TABLE bookings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    booking_date DATE NOT NULL,
    booking_time TIME NOT NULL,
    guest_count INT NOT NULL,
    total_price NUMERIC NOT NULL,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Create "booking_items" table (Junction table)
CREATE TABLE booking_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    booking_id UUID NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id),
    quantity INT NOT NULL,
    unit_price NUMERIC NOT NULL
);

-- Example Data for Bookings (Optional: Uncomment to insert test booking data)
/*
WITH new_booking AS (
    INSERT INTO bookings (customer_name, customer_phone, booking_date, booking_time, guest_count, total_price, status)
    VALUES ('John Doe', '081-111-1111', '2026-06-25', '10:30:00', 2, 10.00, 'pending')
    RETURNING id
)
INSERT INTO booking_items (booking_id, product_id, quantity, unit_price)
SELECT id, 1, 1, 4.50 FROM new_booking
UNION ALL
SELECT id, 2, 1, 5.50 FROM new_booking;
*/
